#
# This file is meant for developers that want to run Platform 6 on their local machine
#
version: '3'

services:

  pgsql:
    container_name: pgsql
    image: postgres:$PGSQL_VERSION
    volumes:
      - $INSTANCE_DATA_PATH/psql.data:/opt/psql.data
    environment:
      - PGDATA=/opt/psql.data
    ports:
      - "5432:5432"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "b2box", "-U", "b2box", "-q"]
      interval: 1s
      timeout: 3s
      retries: 30

  p6core:
    container_name: p6core
    image: $P6CORE_IMAGE_ID
    depends_on:
      - pgsql
      - demobc
    volumes:
      - $INSTANCE_DATA_PATH/p6core.data:/opt/b2box5.data
    links:
      - pgsql:database
    ports:
      - "2222:2222"
      - "5005:5005"
      - "5900:5900"
      - "1099:1099"
    networks:
      - app_net
    environment:
      - S6_KILL_GRACETIME=300000
      - XMX=3g
    labels:
      - traefik.enable=true
      - traefik.http.routers.p6core-https.entrypoints=web-secure
      - traefik.http.routers.p6core-https.rule=Host(`$PLATFORM6_DOMAIN`)
      - traefik.http.routers.p6core-https.tls=true
      - traefik.http.routers.p6core-https.tls.certResolver=p6core
      - traefik.http.routers.p6core-http.entrypoints=web-secure
      - traefik.http.routers.p6core-http.rule=Host(`$PLATFORM6_DOMAIN`)
      - traefik.http.routers.p6core-http.middlewares=p6core-redirect@docker
      - traefik.http.middlewares.p6core-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.p6core-redirect.redirectscheme.permanent=true
      - traefik.http.services.p6core.loadbalancer.server.port=8080

  # The only purpose of this container is to offer TLS support thanks to Let's Encrypt and Traefik
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    depends_on:
      - p6core
    volumes:
      # So that Traefik can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - $INSTANCE_DATA_PATH/web:/etc/traefik
    ports:
      - "80:80"   # Only used by Let's Encrypt even in TLS challenge       
      - "443:443" # Traefik https entry point
      - "444:444" # Traefik admin UI entry point
    networks:
      - app_net

  # Only for testing on a local machine, you don't need this container in production
  #p6proxy:
  #  container_name: p6proxy
  #  image: amalto/b2proxy
  #  depends_on:
  #    - reverse-proxy
  #  environment:
  #    - PROXY_PLAIN_PORT=8480
  #    - LOG_FORMAT=string
  #    - LOG_LEVEL=3
  #    - PROXY_NO_SSL=true
  #    - PROXY_NO_CACHE=true
  #  ports:
  #    - "8480:8480"
  #  networks:
  #    - app_net

  # Local Ethereum blockchain used by the Demo App, delete this container in production
  demobc:
    container_name: demobc
    image: pegasyseng/pantheon:1.2.2
    command:
      --network=dev
      --data-path=/var/lib/pantheon
      --rpc-http-enabled
      --rpc-ws-enabled
      --host-whitelist="all"
      --rpc-http-cors-origins="all"
      --miner-enabled
      --miner-coinbase fe3b557e8fb62b89f4916b721be55ceb828dbd73
    ports:
      - "9545:8545"
    volumes:
      - $INSTANCE_DATA_PATH/p6core.data/demo/pantheon:/var/lib/pantheon
    networks:
      app_net:
        ipv4_address: 172.13.0.20

  # Light Ethereum blockchain explorer used by the Demo App, delete this container in production
  #demoexplorer:
  #  container_name: demoexplorer
  #  image: alethio/ethereum-lite-explorer
  #  environment:
  #    - APP_NODE_URL='http://172.13.0.20:8545'
  #  ports:
  #    - "80:80"
  #  networks:
  #    app_net:
  #      ipv4_address: 172.13.0.200

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.13.0.0/24
