#
# This file is meant for developers that want to run Platform 6 on their local machine
#
version: '3.2'
networks:
  main:
    driver: bridge

volumes:
  data:
  psql:
services:
  pgsql:
    container_name: pgsql
    image: postgres:9.6.1
    volumes:
     - psql:/opt/psql.data
    environment:
     - PGDATA=/opt/psql.data
    ports:
     - "5432:5432"
    networks:
     - main

  platform6:
    container_name: platform6
    image: amalto/platform6:5.15.1
    depends_on:
      - pgsql
    volumes:
     - data:/opt/b2box5.data/
    links:
     - pgsql:database
    ports:
     - "8080:8080"
     - "5005:5005"
     - "5900:5900"
    networks:
     - main
    environment:
     - S6_KILL_GRACETIME=300000
     - XMX=3g

  b2proxy:
    container_name: b2proxy
    image: amalto/b2proxy
    environment:
     - PROXY_PLAIN_PORT=8480
     - LOG_FORMAT=string
     - LOG_LEVEL=3
     - PROXY_NO_SSL=true
     - PROXY_NO_CACHE=true
    links:
     - platform6:b2box
    ports:
     - "8480:8480"
    networks:
     - main
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8480"]
        interval: 5s
        timeout: 2s
        retries: 20
