[global]
  checkNewVersion = true
  sendAnonymousUsage = false


[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  network = "app_net"


# Dashboard config, only activate it in dev, never in production!
[api]
  insecure = true
  dashboard = true
  debug = true


[log]
  level = "DEBUG"
  filePath = "/etc/traefik/traefik.log"


[accessLog]
  filePath = "/etc/traefik/access.log"
  bufferingSize = 100
  format = "json"

  [accessLog.fields]
    defaultMode = "keep"

    [accessLog.fields.headers]
      defaultMode = "keep"


[entryPoints]

  # Used for Let's Encrypt HTTP challenge
  [entryPoints.web]
    address = ":80"

  [entryPoints.web-secure]
    address = ":443"

  # Used for Traefik's admin UI
  [entryPoints.traefik]
    address = ":444"


[certificatesResolvers.p6core.acme]
  email = "development@amalto.com"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.p6core.acme.httpChallenge]
    entryPoint = "web"

