[global]
  checkNewVersion = true
  sendAnonymousUsage = false


[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  network = "app_net"


# Dashboard config, only activate it in dev, never in production!
[api]
  insecure = true
  dashboard = true
  debug = true


[log]
  level = "DEBUG"
  filePath = "/etc/traefik/traefik.log"


[accessLog]
  filePath = "/etc/traefik/access.log"
  bufferingSize = 100


[entryPoints]
  [entryPoints.web]
    address = ":8080"

  [entryPoints.traefik]
    address = ":8481"
