[global]
  checkNewVersion = true
  sendAnonymousUsage = false


[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  network = "app_net"


# Dashboard config, only activate it in dev, never in production!
[api]
  insecure = true
  dashboard = true
  debug = true


[log]
  level = "DEBUG"
  filePath = "/etc/traefik/traefik.log"


[accessLog]
  filePath = "/etc/traefik/access.log"
  bufferingSize = 100

  [accessLog.fields]
    defaultMode = "keep"

    [accessLog.fields.headers]
      defaultMode = "keep"


[entryPoints]

  [entryPoints.web-secure]
    address = ":443"

  # Used for Traefik's admin UI
  [entryPoints.traefik]
    address = ":444"

# Currently TLS challenge doesn't seem to work, that's why port 80 should remain open in Docker
# Here's the command to add a new iptable rule to open port 443 to all:
# iptables -A INPUT -p tcp -m tcp --dport 443 -m comment --comment "Open port 443 for ALL" -m state --state NEW -j ACCEPT
[certificatesResolvers.p6core.acme]
  email = "development@amalto.com"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.p6core.acme.tlsChallenge]
