[global]
  checkNewVersion = true
  sendAnonymousUsage = false


# Dashboard config, only activate it in dev, never in production!
[api]
  insecure = true
  dashboard = true
  debug = true


[log]
  level = "DEBUG"
  filePath = "/etc/traefik/traefik.log"


[accessLog]
  filePath = "/etc/traefik/access.log"
  bufferingSize = 100

  [accessLog.fields]
    defaultMode = "keep"

    [accessLog.fields.headers]
      defaultMode = "keep"


[entryPoints]

  [entryPoints.web]
    address = ":8080"

  # Used for Traefik's admin UI
  [entryPoints.traefik]
    address = ":444"


[providers.file]
  filename = "/etc/traefik/traefik.toml"


[http]

  [http.routers]
    [http.routers.p6core]
      entryPoints = ["web"]
      rule = "PathPrefix(`/`)"
      service = "p6core"

  [http.services]
    [http.services.p6core.loadBalancer]
      [http.services.p6core.loadBalancer.healthCheck]
        path = "/p6/vmstats"
        interval = "10s"
        timeout = "3s"

      [[http.services.p6core.loadBalancer.servers]]
        url = "http://p6core1:8080"

      [[http.services.p6core.loadBalancer.servers]]
        url = "http://p6core2:8080"
